### ISSUE TITLE
SR-13366

### ISSUE THREAD

**Issue by ydnar** [alexpiezo/WebRTC#2]
We encountered this issue when copying an iOS app built in Xcode to a device:

https://bugs.swift.org/browse/SR-13366

From the issue description:

> Closely associated with [SR-13343](https://bugs.swift.org/browse/SR-13343
), cannot install a signed XCFramework containing a Dynamic Library MachO type.  The application builds and fails to launch with a Provisioning Profile error.  
>
> The error is not reproducible when the XCFramework is manually installed and Signed by the App (Embed & Sign setting).
>
> We normally ship the XCFramework with instruction to set the embed setting to Embed and Sign, which as far as I could tell is not a possible configuration through the package manager.

Are the frameworks in this repo signed or unsigned?

**Comment by ydnar** [comment]
The workaround documented here worked for us:

https://pspdfkit.com/guides/ios/current/knowledge-base/library-not-found-swiftpm/

1. Add a build phase to copy frameworks
1. Add a build phase to sign frameworks

**Comment by alexpiezo** [comment]
@ydnar  looks like the issue has been fixed in 12.2 beta 3 this https://forums.swift.org/t/swiftpm-binarytarget-dependency-and-code-signing/38953/36
