### ISSUE TITLE
Please update the library

### ISSUE THREAD

**Issue by YurchukV** [alexpiezo/WebRTC#3]
Please update the library to the current version of GoogleWebRTC (1.1.31999).
Can you enable bitcode support?

**Comment by rditerwich** [comment]
And could I ask for an ios-arm (Apple Silicon) build as well?

**Comment by alopix** [comment]
An updated release for macOS would be really grand

**Comment by pablogeek** [comment]
is this repo no longer supported right?

**Comment by gertjanjansen** [comment]
I have the same question, but it doesn't look like it.

**Comment by alexpiezo** [comment]
Hey, unfortunately I don't have capacity to keep track of updates and release them manually. So I started working on a github action that will take care of keeping repo up to date. Bitcode and M1 will also be added to the next release

**Comment by gertjanjansen** [comment]
Awesome! Thanks a lot.

**Comment by alexpiezo** [comment]
I updated the repo for automatic build with GitHub Actions and also released M86 - M92 with  M1 and Bitcode support
It would be great if someone could test and confirm that everything works as expected on the M1 (both simulator and mac)

**Comment by gertjanjansen** [comment]
@alexpiezo first of all thanks for creating this Swift package. It looks like the automatic builds have stopped working, so this ticket needs to be reopened.

I'm not familiar with Github Actions but I'm happy to dive into it. If I can be of help to fix this, please let me know.
