### ISSUE TITLE
Can't distribute app with bitcode compilation

### ISSUE THREAD

**Issue by masha-b** [alexpiezo/WebRTC#30]
Hi, thanks for your repository. I'm using swift package 94.4606.0 in my project. 
This works great in my app with enabled bitcode. It also runs well on a device from xcode. 
I am failing building .ipa with the "rebuild from bitcode" checkbox enabled. I am getting this error:

ipatool failed with an exception: #<CmdSpec::NonZeroExitException: $ /Applications/Xcode.app/Contents/Developer/usr/bin/python3 
/Applications/Xcode.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin --sdk 
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk -o 
/var/folders/r3/lvjd6dv93k909d0q32xc51440000gn/T/ipatool20211126-2728-7f6an/thinned-out/armv7/Payload/Service112.app/Frameworks/WebRTC.framework/WebRTC --generate-dsym 
/var/folders/r3/lvjd6dv93k909d0q32xc51440000gn/T/ipatool20211126-2728-7f6an/thinned-out/armv7/Payload/Service112.app/Frameworks/WebRTC.framework/WebRTC.dSYM --strip-swift-symbols 
/var/folders/r3/lvjd6dv93k909d0q32xc51440000gn/T/ipatool20211126-2728-7f6an/thinned-in/armv7/Payload/Service112.app/Frameworks/WebRTC.framework/WebRTC
Status: pid 8246 exit 1
Stdout:
    SDK path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk

**Comment by alexpiezo** [comment]
Hi @masha-b sorry to hear that. I could not reproduce this issue in xcode 13. 
Could you please provide more details - xcode and macos versions, distribution method, etc.

**Comment by masha-b** [comment]
Thanks for the prompt response. macOs Big Sur 11.6.1, Xcode version 12.5.1 (12E507).
I will try to distribute it with xcode 13.

**Comment by masha-b** [comment]
Hi, @alexpiezo. Distribution of the application with xcode 13 was successful. It suits me perfectly. Thanks again.
