### ISSUE TITLE
Binary is over 1 GB per iOS platform

### ISSUE THREAD

**Issue by holly-acquire** [alexpiezo/WebRTC#32]
The Mac binary is 25 MB. The iOS ones are 1.2 and 1.8 GB each. That doesn't seem right.

**Comment by tylerjames** [comment]
It's that big because it's compiled with bitcode enabled. It's ridiculous but it's just that huge

**Comment by alexpiezo** [comment]
Yeah, it's just bitcode and multiple architectures for different platforms in one xcframework. Of course the size of the final iOS binary (estimated App Store file size) will be less than 25MB
