### ISSUE TITLE
 While building for Mac Catalyst, no library for this platform was found in 'WebRTC.xcframework'.

### ISSUE THREAD

**Issue by nikhil191090** [alexpiezo/WebRTC#4]
Getting this issue while try to run on mac

**Comment by nikhil191090** [comment]
@alexpiezo Please Help i am kind of stuck here

**Comment by alexpiezo** [comment]
@nikhil191090 Unfortunately this build doesn't support Mac Catalyst. At least until official WebRTC supports the arch

**Comment by alexpiezo** [comment]
Duplicate of #1
