### ISSUE TITLE
Failed on macOS 11.2.3, Xcode 12.4

### ISSUE THREAD

**Issue by gaojinhsu** [alexpiezo/WebRTC#6]
first, I modified the `find_sdk.py` like this
![image](https://user-images.githubusercontent.com/2178687/112983891-c7e62900-9190-11eb-9285-db46ae54ba23.png)
then I followed your guide,  but failed. ```
 error: use of undeclared identifier '__FILE_NAME__'
    NSAssert([key isKindOfClass:[NSString class]], 
```

**Comment by alexpiezo** [comment]
I have added some scripts to build the framework. If you would like to build it locally, please have a look at [build.sh](https://github.com/alexpiezo/WebRTC/blob/9af5e436f85ea1a4b3a83e661b210cfac1b51e93/scripts/build.sh) and [create_xcframework.sh](https://github.com/alexpiezo/WebRTC/blob/9af5e436f85ea1a4b3a83e661b210cfac1b51e93/scripts/create_xcframework.sh)

You can also fork the repo and run the [action](https://github.com/alexpiezo/WebRTC/blob/9af5e436f85ea1a4b3a83e661b210cfac1b51e93/.github/workflows/build_mstones.yml)  to build with different parameters
